-- AlterTable
ALTER TABLE `order` ADD COLUMN `addressId` VARCHAR(191) NULL,
    ADD COLUMN `paymentMethod` ENUM('CREDIT_CARD', 'DEBIT_CARD', 'RAZORPAY', 'COD') NULL,
    ADD COLUMN `paymentStatus` ENUM('COMPLETED', 'INPROGRESS', 'CANCLED') NOT NULL DEFAULT 'INPROGRESS';

-- AddForeignKey
ALTER TABLE `Order` ADD CONSTRAINT `Order_addressId_fkey` FOREIGN KEY (`addressId`) REFERENCES `Address`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
